version: "3.9"
services:
  dev:
    image: pytorch/pytorch:1.13.0-cuda11.6-cudnn8-devel
    working_dir: /workspace
    volumes:
      - .:/workspace
    environment:
      - TZ=Asis/Seoul
    shm_size: '16gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    stdin_open: true
